coverage:
  paths:
    - coverage/.resultset.json
codeToTestRatio:
  code:
    - '**/*.rb'
    - '!test/**/*.rb'
  test:
    - 'test/**/*_test.rb'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: false
body:
  if: true
#comment:
#  if: is_pull_request
#  deletePrevious: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
timeout: 5min
summary:
  if: true
