name: Test for memory leaks

on: [push, pull_request]

jobs:
  build:
    name:
      Valgrind
    runs-on: ubuntu-latest
    env:
      CC: gcc

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -y install valgrind
        sudo apt-get -y install zlib1g-dev

    - name: test valgrind
      run: make test_valgrind V=1 -j 2
